[package]
name = "airupoe"
version = "0.1.0"
authors = ["sisungo <otelve@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
nng = "0.5.1"
once_cell = "1.5.2"
toml = "0.5.8"
